import { EasingValues, RepeatProps, SpringProps } from './types';
declare const DEFAULT_TOTAL_DURATION = 1000;
declare const DEFAULT_DELAY = 0;
declare const DEFAULT_OFFSET = 0;
declare const DEFAULT_WIDTH = 0;
declare const DEFAULT_HEIGHT = 0;
declare const DEFAULT_HIDE_VIEW = false;
declare const DEFAULT_EASING_VALUES: EasingValues;
declare const DEFAULT_REPEAT_PROPS: RepeatProps;
declare const DEFAULT_SPRING_PROPS: SpringProps;
export { DEFAULT_TOTAL_DURATION, DEFAULT_DELAY, DEFAULT_OFFSET, DEFAULT_WIDTH, DEFAULT_HEIGHT, DEFAULT_HIDE_VIEW, DEFAULT_EASING_VALUES, DEFAULT_REPEAT_PROPS, DEFAULT_SPRING_PROPS, };
